name: a

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: frangio/test-repo-2/foobar@master
        env:
          GH_TOKEN: ${{ github.token }}
